name: Alegra daily report

on:
  schedule:
    # 07:00 a. m. Bogotá (12:00 UTC), de lunes a sábado
    - cron: "0 12 * * 1-6"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      ALEGRA_API_EMAIL: ${{ secrets.ALEGRA_API_EMAIL }}
      ALEGRA_API_TOKEN: ${{ secrets.ALEGRA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install -r requirements.txt

      - name: Build / update report
        run: python last_purchase_report.py

      - name: Commit updated CSV + state
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add clients_last_purchase.csv state.json
          if git diff --cached --quiet; then
            echo "Sin cambios que commitear"
          else
            git commit -m "chore: daily Alegra report"
            git push
          fi