name: Alegra daily report (Supabase)

on:
  schedule:
    # 07:00 a. m. Bogotá (12:00 UTC), de lunes a sábado
    - cron: "0 12 * * 1-6"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      # Alegra API
      ALEGRA_API_EMAIL: ${{ secrets.ALEGRA_API_EMAIL }}
      ALEGRA_API_TOKEN: ${{ secrets.ALEGRA_API_TOKEN }}
      # Supabase
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Alegra report
        run: python last_purchase_report.py

      - name: Report completion
        run: echo "✅ Reporte completado y guardado en Supabase"
